name: 'PR noti'

on:
  pull_request:
    types: [opened, reopened]
    branches: [master, main, staging]

jobs:
  noti:
    name: noti
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        username: Github-Police
        args: |
          Pull Request in ${{github.repository}}
          FROM: ${{github.head_ref}} -> TO: ${{github.base_ref}}
          BY @${{github.event.pull_request.user.login}} | ${{ github.event.pull_request.html_url }}
